### ISSUE TITLE
 PowerShell Portable Core Feedback

### ISSUE THREAD

**Issue by ALIENQuake** [rannn505/child-shell#77]
Hey, I don't see any changes which would reflect #72 so I'm sharing additional feedback:

- the options.pwsh and options.pwshPrev should be evaluated as logical OR - if dev want's to use pwshPrev, he shouldn't need to set pwsh additionally
- for  PowerShell Portable, dev should be able to simply extract zip into 'powershell' or 'powershell-preview' and it should be an indication to use it by node shell process spawning

@rannn505 Do you want PR with proposed changes?

**Comment by rannn505** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add post-install script](https://trello.com/c/hI57gpg2/53-add-post-install-script)
